name: "eunomia-ds-agent-provider"

services:
  provider-vault:
    image: hashicorp/vault:1.21
    container_name: provider-vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./../../vault/provider/config:/vault/config
      - ./../../vault/provider/data:/vault/file
    environment:
      VAULT_CACERT: /vault/config/root-ca.pem
      VAULT_LOCAL_CONFIG: >
        {
          "storage": { "file": { "path": "/vault/file" } },
          "listener": [{
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_cert_file": "/vault/config/vault-cert.pem",
              "tls_key_file": "/vault/config/vault-key.pem",
              "tls_client_ca_file": "/vault/config/vault-ca.pem"
            }
          }],
          "ui": true,
          "api_addr": "https://127.0.0.1:8200",
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h"
        }
    command: server

  provider-db:
    container_name: "provider-db"
    image: "postgres"
    restart: always
    env_file:
      - ./../../static/envs/provider/db.env

  provider-redis:
    image: redis:alpine
    restart: always
    container_name: provider-redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass ds_core_provider_redis
      --user admin on >ds_core_provider_redis ~* +@all

  # =========================
  # Setup job (one-shot)
  # =========================
  provider-setup:
    container_name: provider-setup
    image: rmenendez8/rainbow:v1.3.0
    command: ["setup", "-e", "/app/static/config/core.provider.yaml"]
    volumes:
      - ./../../static/config/provider/prod:/app/static/config
      - ./../../static/specs/agent:/app/static/specs
      - ./../../static/policy_templates:/app/static/policy_templates
      - ./../../vault/provider:/app/vault
    depends_on:
      - provider-db
      - provider-vault
      - provider-redis
    env_file:
      - ./../../static/envs/provider/core.env
    restart: "no"

  # =========================
  # Main service
  # =========================
  provider:
    container_name: provider
    image: rmenendez8/rainbow:v1.3.0
    command: ["start", "-e", "/app/static/config/core.provider.yaml"]
    ports:
      - "443:443"
    volumes:
      - ./../../static/config/provider/prod:/app/static/config
      - ./../../static/specs/agent:/app/static/specs
      - ./../../static/policy_templates:/app/static/policy_templates
      - ./../../vault/provider:/app/vault
    depends_on:
      provider-setup:
        condition: service_completed_successfully
      provider-db:
        condition: service_started
      provider-vault:
        condition: service_started
      provider-redis:
        condition: service_started
    env_file:
      - ./../../static/envs/provider/core.env
    environment:
      RUST_BACKTRACE: full
