name: "eunomia-ds-agent-consumer"

services:
  consumer-vault:
    image: hashicorp/vault:1.21
    container_name: consumer-vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./../../vault/consumer/config:/vault/config
      - ./../../vault/consumer/data:/vault/file
    environment:
      VAULT_CACERT: /vault/config/root-ca.pem
      VAULT_LOCAL_CONFIG: >
        {
          "storage": { "file": { "path": "/vault/file" } },
          "listener": [{
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_cert_file": "/vault/config/vault-cert.pem",
              "tls_key_file": "/vault/config/vault-key.pem",
              "tls_client_ca_file": "/vault/config/vault-ca.pem"
            }
          }],
          "ui": true,
          "api_addr": "https://127.0.0.1:8200",
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h"
        }
    command: server

  consumer-db:
    container_name: "consumer-db"
    image: "postgres"
    restart: always
    env_file:
      - ./../../static/envs/consumer/db.env

  consumer-redis:
    image: redis:alpine
    restart: always
    container_name: consumer-redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass ds_core_consumer_redis
      --user admin on >ds_core_consumer_redis ~* +@all

  # =========================
  # Setup job (one-shot)
  # =========================
  consumer-setup:
    container_name: consumer-setup
    image: rmenendez8/rainbow:v1.3.0
    command: ["setup", "-e", "/app/static/config/core.consumer.yaml"]
    volumes:
      - ./../../static/config/consumer/prod:/app/static/config
      - ./../../static/specs/agent:/app/static/specs
      - ./../../static/policy_templates:/app/static/policy_templates
      - ./../../vault/consumer:/app/vault
    depends_on:
      - consumer-db
      - consumer-vault
      - consumer-redis
    env_file:
      - ./../../static/envs/consumer/core.env
    restart: "no"

  # =========================
  # Main service
  # =========================
  consumer:
    container_name: consumer
    image: rmenendez8/rainbow:v1.3.0
    command: ["start", "-e", "/app/static/config/core.consumer.yaml"]
    ports:
      - "443:443"
    volumes:
      - ./../../static/config/consumer/prod:/app/static/config
      - ./../../static/specs/agent:/app/static/specs
      - ./../../static/policy_templates:/app/static/policy_templates
      - ./../../vault/consumer:/app/vault
    depends_on:
      consumer-setup:
        condition: service_completed_successfully
      consumer-db:
        condition: service_started
      consumer-vault:
        condition: service_started
      consumer-redis:
        condition: service_started
    env_file:
      - ./../../static/envs/consumer/core.env
    environment:
      RUST_BACKTRACE: full
